# Generated by Django 4.2.5 on 2023-10-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('P', 'Prestador'), ('C', 'Contratante')], max_length=1)),
                ('nome_completo', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, unique=True)),
            ],
        ),
    ]
