# Generated by Django 4.2.5 on 2023-10-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(choices=[('P', 'Prestador'), ('C', 'Contratante')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='modalidade',
        ),
    ]
